### ISSUE TITLE
Remove documentation build directory

### ISSUE THREAD

**Issue by jcfr** [ETS-vis-interactive/SlicerPRISMRendering#2]
I suggest to remove the build directory from the source tree: https://github.com/ETS-vis-interactive/SlicerPRISMRendering/tree/master/docs/build

Indeed the documentation is now available here: https://githubcomets-vis-interactiveslicerprismrendering.readthedocs.io/en/latest/

**Comment by Tiphainejh** [comment]
Hello, I am not sure how readthedocs works but from my understanding, the documentation is build automatically from the repository so will it still work if I remove it?

**Comment by jcfr** [comment]
>the documentation is build automatically from the repository so will it still work if I remove it?

Indeed, it will work as expected. You can safely remove it.

After setting up build of Pull request submitted to your repository, you will  be able to confirm this by yourself. See https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by Tiphainejh** [comment]
Okay great thank you!

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/ETS-vis-interactive/SlicerPRISMRendering/commit/87aee4d5aa02694ec1e9b770556a2a54bf5c4a3f#diff-e3e2a9bfd88566b05001b02a3f51d286
